# This is a basic workflow to help you get started with Actions

name: RSS_Update

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "gh-pages" ]
  pull_request:
    branches: [ "gh-pages" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download a file
        uses: carlosperate/download-file-action@v1
        with:
          file-url: 'https://thesharingspace.de/feed/mp3/'
          # file-url: 'https://maxwindt.github.io/TheSharingSpace/feed.rss'
          file-name: 'mp3.rss'
          location: 'feed/.'
      - name: Print the file path (new-folder-to-be-created/new_filename.tar.gz)
        run: echo "The file was downloaded to ${{ steps.download-file.outputs.file-path }}"
      - run: |
          ls
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: ${{ github.workspace }}
          branch: gh-pages
          token: ${{ secrets.PUSH_FILE_TOKEN }}
